### ISSUE TITLE
Page Loader is processor intensive.

### ISSUE THREAD

**Issue by tdaubs** [robertleeplummerjr/CanvasWorker#1]
I recommend dropping the pageloader from http://codepen.io/biht/pen/azQVxQ.  It's processor intensive and seems counterintuitive to what CanvasWorker is trying to accomplish.  Don't run a heater on one side of your house while running an air conditioner on the other side.  :)

**Comment by robertleeplummerjr** [comment]
The loader uses CSS transitions, which use GPU for rendering, and little CPU, while the web workers uses strictly CPU.  So even if the loader is process intensive, it isn't using the same threads as the CanvasWorker...  Also, the colors are pretty :).

**Comment by tdaubs** [comment]
Monitor the CPU use prior to opening the pageloader compared to CPU use after loading pageloader.  My CPU spikes to over 50% use on initial opening and then hovers around 30-40% percent.  That's insane for a simple pageloader.  I don't think enough is offloaded to the GPU plus it's very counterintuitive to use a processor intensive page loader for code that is supposed to free up processor cycles.  Plus... it's completely unnecessary to showcase the core advantange of using canvasworker. Better to clean up all unnecessary elements and just present your solution.  Remember the KISS prinicipal.

Finally... the pageloader isn't that pretty anyway.

It may be brutal... but at least its honesty.  :)

**Comment by robertleeplummerjr** [comment]
Touché.  I'll remove it asap.  Thanks for your analisys.

**Comment by tdaubs** [comment]
You have chosen wisely.
